In [1]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [2]:
data = np.array([['Low'], ['Medium'],['High'], ['Low'], ['High']])
data

array([['Low'],
       ['Medium'],
       ['High'],
       ['Low'],
       ['High']], dtype='<U6')

In [3]:
OE = OrdinalEncoder(categories=[['Low', 'Medium', 'High']], dtype=int)

In [4]:
OE.fit_transform(data)

array([[0],
       [1],
       [2],
       [0],
       [2]])

#### One Hot Encoding

OneHotEncoder class

In [5]:
data = np.array([['Apple'], ['Orange'], ['Mango']])

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
OHE = OneHotEncoder(sparse_output=False, dtype=int)

In [8]:
OHE.fit_transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

#### Pandas

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame({'Color':['Black', 'Blue', 'Red', 'Orange'],
                   'sr no':[1, 2, 3, 4]})
df

    Color  sr no
0   Black      1
1    Blue      2
2     Red      3
3  Orange      4

In [11]:
df = pd.get_dummies(df, dtype=int)

In [12]:
df

   sr no  Color_Black  Color_Blue  Color_Orange  Color_Red
0      1            1           0             0          0
1      2            0           1             0          0
2      3            0           0             0          1
3      4            0           0             1          0

#### Label Encoding

For Converting nominal data into orders

In [13]:
colors = ['Black', 'Red', 'Green', 'Blue', 'Orange']

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit_transform(colors)  #alphabetically

array([0, 4, 2, 1, 3])